#!/bin/bash
set -eux

export MONGODB_VERSION=3.6.15
export MONGODB_PATH=${HOME}/mongodb-$MONGODB_VERSION
export PATH=${MONGODB_PATH}/bin:$PATH

${MONGODB_PATH}/bin/mongod --dbpath ${MONGODB_PATH}/data/db &

exec "$@"

