#!/bin/bash
set -eux

source ./binder/version.txt

export MONGODB_VERSION
export MONGODB_PATH=${CONDA_DIR}/mongodb-$MONGODB_VERSION
export PATH=${MONGODB_PATH}/bin:$PATH

${MONGODB_PATH}/bin/mongod --dbpath ${MONGODB_PATH}/data/db &

exec "$@"

